# Generated by Django 2.1 on 2018-08-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('size', models.CharField(max_length=50, null=True)),
                ('age_group', models.CharField(max_length=50, null=True)),
                ('colour', models.CharField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=5, default=0.0, max_digits=12)),
                ('brand_name', models.CharField(max_length=50, null=True)),
                ('season', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
